### ISSUE TITLE
Wrong parameter replacement due to how the API returns it

### ISSUE THREAD

**Issue by sabino** [timothypratley/happygapi#1]
Hello there!

I've been trying to use this library and I've identified that some of the functions that uses the `util/get-url` are not properly replacing the parameters.

For instance, I've tried using the `happygapi.serviceusage.services/enable$` function and it gives me a parsing error, which means it didn't respond with a json:

```
Execution error (JsonParseException) at com.fasterxml.jackson.core.JsonParser/_constructError (JsonParser.java:1840).
Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (StringReader); line: 1, column: 2]
```

The main issue is that the replacement is being without accounting for the prefix `+`, which could be removed when doing the replace in the `get-url` function:

```clojure
(happy.util/get-url
  "https://serviceusage.googleapis.com/"
  "v1/{+name}:enable"
  #{:name}
  {:name "projects/sabino-proj-4clj/services/bigquery.googleapis.com"})
```
Outputs:
```
"https://serviceusage.googleapis.com/v1/{+name}:enable"
```

I'll suggest something on a PR.

**Comment by timothypratley** [comment]
Thank you!

**Comment by timothypratley** [comment]
Hi @sabino 


Just letting you know I've pushed version `0.4.8` to clojars with a fix for this behavior.

Sorry that it took me so long to get back to you about this!


Sincerely,
Timothy
